"""Normalized centerline SVG preview (fixed styling; no source SVG styles)."""

from __future__ import annotations

from collections.abc import Sequence

from shapely.geometry import GeometryCollection, LineString, MultiLineString, MultiPolygon, Polygon
from shapely.ops import transform as transform_geometry

from lettersign.centerline import geometry_to_svg_path
from lettersign.geometry import Marker

BaseGeometry = Polygon | MultiPolygon | LineString | MultiLineString | GeometryCollection

GENERATED_FILE_COMMENT = "Generated by lettersign (normalized centerline preview)."

_OUTLINE_STROKE = "#000000"
_CENTERLINE_STROKE = "#ff0000"
_MARKER_FILL_STROKE = "#008000"
_OUTLINE_STROKE_WIDTH = 1.0


def render_centerline_svg(
    *,
    view_box: tuple[float, float, float, float],
    outlines: BaseGeometry,
    centerline: BaseGeometry,
    markers: Sequence[Marker],
    led_channel_width: float,
) -> str:
    """Return SVG markup with black outlines, red centerline, and green marker circles."""
    min_x, min_y, width, height = view_box
    vb = _format_view_box(min_x, min_y, width, height)
    outline_d = geometry_to_svg_path(_to_svg_display_geometry(outlines, view_box))
    centerline_d = geometry_to_svg_path(
        _to_svg_display_geometry(centerline, view_box),
        smooth_lines=False,
    )

    lines: list[str] = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- {GENERATED_FILE_COMMENT} -->",
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{vb}">',
        "  " + _outline_path_element(outline_d, stroke_width=_OUTLINE_STROKE_WIDTH),
        "  " + _centerline_path_element(centerline_d, stroke_width=led_channel_width),
    ]
    for marker in markers:
        lines.append("  " + _marker_circle_element(marker, view_box=view_box))
    lines.append("</svg>")
    return "\n".join(lines) + "\n"


def _format_view_box(min_x: float, min_y: float, width: float, height: float) -> str:
    return f"{min_x:.6g} {min_y:.6g} {width:.6g} {height:.6g}"


def _outline_path_element(d: str, *, stroke_width: float) -> str:
    w = f"{stroke_width:.6g}"
    return f'<path d="{d}" fill="none" stroke="{_OUTLINE_STROKE}" stroke-width="{w}"/>'


def _centerline_path_element(d: str, *, stroke_width: float) -> str:
    w = f"{stroke_width:.6g}"
    return (
        f'<path d="{d}" fill="none" stroke="{_CENTERLINE_STROKE}" stroke-width="{w}" '
        'stroke-linecap="round" stroke-linejoin="round"/>'
    )


def _marker_circle_element(marker: Marker, *, view_box: tuple[float, float, float, float]) -> str:
    r = f"{marker.radius_mm:.6g}"
    cx = f"{marker.position.x:.6g}"
    cy = f"{_to_svg_display_y(marker.position.y, view_box):.6g}"
    return (
        f'<circle cx="{cx}" cy="{cy}" r="{r}" '
        f'fill="{_MARKER_FILL_STROKE}" stroke="{_MARKER_FILL_STROKE}"/>'
    )


def _to_svg_display_geometry(
    geometry: BaseGeometry,
    view_box: tuple[float, float, float, float],
) -> BaseGeometry:
    return transform_geometry(lambda x, y, z=None: (x, _to_svg_display_y(y, view_box)), geometry)


def _to_svg_display_y(y: float, view_box: tuple[float, float, float, float]) -> float:
    _min_x, min_y, _width, height = view_box
    return min_y + height - (y - min_y)
