"""Generate OpenSCAD text for `<name>_data.scad`, user wrapper, and shared helper."""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path

from lettersign.geometry import Point
from lettersign.project import ProjectPaths
from lettersign.scad_assets import common_scad_text
from lettersign.scad_geometry import ScadModel, ScadPathPart, ScadPolygon, ScadPost

GENERATED_DATA_SCAD_COMMENT = "Generated by lettersign (OpenSCAD geometry data)."

USER_WRAPPER_COMMENT = (
    "// User-editable wrapper. Invokes geometry from *_data.scad; safe to customize."
)


def render_data_scad(model: ScadModel) -> str:
    """Return `<name>_data.scad` source for *model* (generated; overwritten on build)."""
    prefix = _scad_identifier_prefix(model.project_name)
    lines: list[str] = [
        f"// {GENERATED_DATA_SCAD_COMMENT}",
        "use <../lettersign_common.scad>",
        "",
        f"{prefix}_height = {_fmt(model.height_mm)};",
        f"{prefix}_led_channel_width = {_fmt(model.led_channel_width_mm)};",
        f"{prefix}_post_height = {_fmt(model.post_height_mm)};",
        "",
    ]
    for part in model.parts:
        lines.extend(_render_path_part(part, height_var=f"{prefix}_height"))
    invocations = "\n    ".join(f"{p.name}_3d();" for p in model.parts)
    lines.extend(
        [
            f"module {prefix}_3d() {{",
            f"  {invocations}",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def render_wrapper_scad(project_name: str) -> str:
    """Return default `<name>.scad` wrapper text (user-owned; create only when absent)."""
    safe_name = Path(project_name).name  # single segment from validated name
    data_file = f"{safe_name}_data.scad"
    prefix = _scad_identifier_prefix(safe_name)
    return f"{USER_WRAPPER_COMMENT}\n\nuse <{data_file}>\n\n{prefix}_3d();\n"


def write_scad_outputs(paths: ProjectPaths, model: ScadModel) -> None:
    """Write canonical common helper (always), data SCAD (always), wrapper (create only).

    Existing wrapper SCAD must not be modified.
    """
    paths.common_scad.parent.mkdir(parents=True, exist_ok=True)
    paths.common_scad.write_text(common_scad_text(), encoding="utf-8")

    paths.project_dir.mkdir(parents=True, exist_ok=True)
    paths.data_scad.write_text(render_data_scad(model), encoding="utf-8")

    if not paths.wrapper_scad.exists():
        paths.wrapper_scad.write_text(render_wrapper_scad(model.project_name), encoding="utf-8")


def _render_path_part(part: ScadPathPart, *, height_var: str) -> list[str]:
    slug = part.name
    sep = "// " + "=" * (len(slug) + 14)
    return [
        sep,
        f"// {slug}",
        sep,
        "",
        f"module {slug}_outline() {{",
        *_indent_block(_polygon_statements(part.outline), 2),
        "}",
        "",
        f"module {slug}_channel() {{",
        *_indent_block(_channel_body(part.channels), 2),
        "}",
        "",
        f"module {slug}_posts() {{",
        *_indent_block(_posts_body(part.posts), 2),
        "}",
        "",
        f"module {slug}_3d() {{",
        *_indent_block(_path_3d_body(slug, part.channels, height_var), 2),
        "}",
        "",
        "",
    ]


def _path_3d_body(
    slug: str,
    channels: tuple[ScadPolygon, ...],
    height_var: str,
) -> list[str]:
    if channels:
        return [
            "union() {",
            "  difference() {",
            "    linear_extrude(height=" + height_var + ")",
            f"      {slug}_outline();",
            "    translate([0, 0, -0.1])",
            "      linear_extrude(height=" + height_var + " + 0.2)",
            f"        {slug}_channel();",
            "  }",
            f"  {slug}_posts();",
            "}",
        ]
    return [
        "union() {",
        "  linear_extrude(height=" + height_var + ")",
        f"    {slug}_outline();",
        f"  {slug}_posts();",
        "}",
    ]


def _polygon_statements(poly: ScadPolygon) -> list[str]:
    pts = _format_points_array(poly.points)
    paths_str = _format_paths_array(poly.paths)
    return [f"polygon(points={pts}, paths={paths_str});"]


def _channel_body(channels: tuple[ScadPolygon, ...]) -> list[str]:
    if not channels:
        return ["// no channel geometry in this path"]
    if len(channels) == 1:
        return _polygon_statements(channels[0])
    inner: list[str] = ["union() {"]
    for poly in channels:
        for line in _polygon_statements(poly):
            inner.append("  " + line)
    inner.append("}")
    return inner


def _posts_body(posts: tuple[ScadPost, ...]) -> list[str]:
    if not posts:
        return ["// no posts in this path"]
    if len(posts) == 1:
        return [_post_call(posts[0])]
    inner: list[str] = ["union() {"]
    for p in posts:
        inner.append("  " + _post_call(p))
    inner.append("}")
    return inner


def _post_call(p: ScadPost) -> str:
    x = _fmt(p.position.x)
    y = _fmt(p.position.y)
    r = _fmt(p.radius_mm)
    h = _fmt(p.height_mm)
    return f"lettersign_post([{x}, {y}], {r}, {h});"


def _format_points_array(points: Sequence[Point]) -> str:
    if not points:
        return "[]"
    rows = [f"    [{_fmt(p.x)}, {_fmt(p.y)}]," for p in points]
    return "[\n" + "\n".join(rows) + "\n  ]"


def _format_paths_array(paths: tuple[tuple[int, ...], ...]) -> str:
    if not paths:
        return "[]"
    rows = [f"    [{', '.join(str(i) for i in path)}]," for path in paths]
    return "[\n" + "\n".join(rows) + "\n  ]"


def _indent_block(lines: Sequence[str], spaces: int) -> list[str]:
    pad = " " * spaces
    out: list[str] = []
    for line in lines:
        out.append(pad + line if line.strip() else line)
    return out


def _fmt(value: float) -> str:
    return f"{value:.6g}"


def _scad_identifier_prefix(project_name: str) -> str:
    """Map project directory name to a safe OpenSCAD identifier prefix."""
    s = project_name.replace("-", "_")
    out: list[str] = []
    for ch in s:
        if ch.isalnum() or ch == "_":
            out.append(ch)
        elif not out and ch in {".", " "}:
            continue
        else:
            out.append("_")
    raw = "".join(out).strip("_")
    if not raw:
        return "project"
    if raw[0].isdigit():
        return f"p_{raw}"
    return raw
